services:
    backend:
        container_name: go-practice
        build:
            dockerfile: ./backend/Dockerfile
            context: .
        stdin_open: true
        ports:
            - "8080:8080"
        tty: true
        depends_on:
            - db
        env_file:
            - .env
        volumes:
            - type: bind
              source: ./backend/src
              target: /go/app/src

    db:
        container_name: db-practice
        build:
            dockerfile: ./db/Dockerfile
            context: .
        stdin_open: true
        ports:
            - "33060:3306"
        tty: true
        platform: linux/x86_64
        volumes:
            - type: volume
              source: maria-volume
              target: /var/lib/mysql
            - type: bind
              source: ./db/init.sql
              target: /docker-entrypoint-initdb.d/init.sql
        env_file:
            - .env

volumes:
    maria-volume:
        name: mariadb-volume
